spring:
  application:
    name: apikeysdemo
  temporal:
    namespace: ${tmprl.cloud.namespace}
    connection:
      target: ${tmprl.cloud.target}
      api-key: ${tmprl.cloud.key}
      enable-https: true
    workers-auto-discovery:
      packages:
        - com.example.apikeysdemo.workflows
management:
  endpoints:
    web:
      exposure:
        include: prometheus
tmprl:
  cloud:
    key: <your_key>
    target: <your_target>
    namespace: <your_namespace>